spring:
  application:
    name: supermarket
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/supermarket
    username: root
    password: astrie123

server:
  port: 8093